Get pseudobulk api
stemangiola/CuratedAtlasQueryR pull request #137
Opened 2024-04-16 06:14 UTC by myushen

solve issue #136 
get_pseudobulk API takes pre-calculated summarized experiment assays for selected sample IDs, combines them and returns a merged summarized experiment. The pre-calculated summarized experiment assays will be stored in a cloud container in the future.

2024-04-16 07:15 UTC, multimeric requested changes
Note also that `SingleCellExperiment` is a subclass of `SummarisedExperiment`, so if it's possible to write code that works on a `SummarisedExperiment`, then it will automatically work on both. This can help you simplify code and also documentation.

2024-04-16 07:15 UTC, multimeric commented on R/counts.R
> +#'   assays argument
A lot of this is a copy from `get_single_cell_experiment`. I would consider reading https://cran.r-project.org/web/packages/roxygen2/vignettes/reuse.html. Specifically, I can see `@inheritParams` being useful.

2024-04-16 07:15 UTC, multimeric commented on R/counts.R
> +#'                sample_ == '07605571f51519f71da03704f056fa43')
```suggestion
#'         filter(sample_ %in% c('068502277538ef5559154b543167fefa', '07605571f51519f71da03704f056fa43'))
```

2024-04-16 07:15 UTC, multimeric commented on R/counts.R
> +  subdirs <- assay_map[assays]
There is a lot of duplication of validation logic and other things here. I would rather see this refactored into a separate function that is called by both `get_single_cell_experiment` and `get_pseudobulk`.

2024-04-26 02:15 UTC, stemangiola commented
@multimeric any further concern?

2024-04-26 02:16 UTC, stemangiola commented
I did not export fibrosis pseudobulk yet, @myushen did you test with fibrosis?

2024-04-28 23:33 UTC, myushen commented
> I did not export fibrosis pseudobulk yet, @myushen did you test with fibrosis?

No, it is only based on cellxgene.

2024-04-29 05:17 UTC, multimeric commented
I'm still concerned that `group_to_sme` is a near-exact copy of `group_to_sce` and the same for `get_pseudobulk` and `get_single_cell_experiment`. I see little reason why you can't consolidate these pairs of functions into one function, considering that you are working with a `SummarizedExperiment` in both cases.

2024-04-29 05:55 UTC, myushen commented
> I'm still concerned that `group_to_sme` is a near-exact copy of `group_to_sce` and the same for `get_pseudobulk` and `get_single_cell_experiment`. I see little reason why you can't consolidate these pairs of functions into one function, considering that you are working with a `SummarizedExperiment` in both cases.

I'll wrap up into one function, but do we want to separate function names for get_sce and get_pseudobulk? @stemangiola

2024-04-30 01:33 UTC, stemangiola commented
> > I'm still concerned that `group_to_sme` is a near-exact copy of `group_to_sce` and the same for `get_pseudobulk` and `get_single_cell_experiment`. I see little reason why you can't consolidate these pairs of functions into one function, considering that you are working with a `SummarizedExperiment` in both cases.
> 
> I'll wrap up into one function, but do we want to separate function names for get_sce and get_pseudobulk? @stemangiola

Are we asking here if

`get_single_cell_experiment` and `get_pseudobulk` should be the same function.

If this is the question I think that is beneficial keeping them separate.

2024-05-16 05:31 UTC, multimeric reviewed
Needs a test for the `get_pseudobulk` workflow.

Also this isn't a blocker, but I'd like to see some of the assay-specific logic (`if (type == "sce")`) moved into the calling function like `get_single_cell_experiment`, so that `get_summarized_experiment` remains decoupled from the subclass we're dealing with.

2024-05-16 05:31 UTC, multimeric commented on R/counts.R
> +#' or pseudobulk.
```suggestion
#' @param type A character vector of length one. Either "sce" for Single Cell Experiment,
#' or "pseudobulk".
```

2024-05-16 05:31 UTC, multimeric commented on R/counts.R
> +      pull(file_id_col) |>
```suggestion
      pull(.data$file_id_col) |>
```

2024-05-16 05:31 UTC, multimeric commented on R/counts.R
> +#' @return A Summarized Experiment object
```suggestion
#' @return A `SummarizedExperiment` object
```

2024-05-16 05:31 UTC, multimeric commented on R/counts.R
> +      column_to_rownames("original_sample_id")
This is just for readability.
```suggestion
    new_coldata <- df |>
        select(-dplyr::all_of(cell_level_anno)) |>
        distinct() |>
        mutate(
            sample_identifier = glue("{sample_}___{cell_type_harmonised}"),
            original_sample_id = .data$sample_identifier
        ) |>
        column_to_rownames("original_sample_id")
```

2024-05-16 05:58 UTC, stemangiola commented
> Needs a test for the `get_pseudobulk` workflow.
> 
> Also this isn't a blocker, but I'd like to see some of the assay-specific logic (`if (type == "sce")`) moved into the calling function like `get_single_cell_experiment`, so that `get_summarized_experiment` remains decoupled from the subclass we're dealing with.

Thanks. Maybe @myushen do the tests, and we tackle the second point from @multimeric  in the future. We have to proceed, with other tasks.

2024-05-20 05:47 UTC, multimeric approved these changes

2024-05-20 05:55 UTC, merged

2024-05-20 05:55 UTC, stemangiola commented
Great team work fellas!