update validation columns for get_sce
stemangiola/CuratedAtlasQueryR pull request #143
Opened 2024-06-03 07:37 UTC by myushen

separate the column validation from `get_sce` and `get_pseudobulk`

2024-06-03 07:43 UTC, stemangiola requested changes
here we are overengineering, and creating complex general functions, that should not be.

The validation in this case should be in get_single_Cell_experiment function.

I don't think `param_validation ` should exist, you can add the context of the validation in the `get_single_Cell_experiment` directly

2024-06-03 07:50 UTC, myushen commented
separating `param_validation` from the main function can minimize a few lines of code duplication for `get_sce` and `get_pseudobulk`  I think

2024-06-03 08:12 UTC, stemangiola commented
> separating `param_validation` from the main function can minimize a few lines of code duplication for `get_sce` and `get_pseudobulk` I think

Agree, but in this case this minimidsation has a big cost of complexity, and code clarity. In our case `get_single_Cell_experiment ` if basically empty, so a validation header is acceptable.

2024-06-04 03:36 UTC, stemangiola commented on R/counts.R
> -  repository <- if (type == "sce") COUNTS_URL else pseudobulk_url
I propose this function.

```r
get_data_container <- function(
    data,
    assays = "counts",
    cache_directory = get_default_cache_dir(),
    repository, # url
    grouping_column, # file_id_db, file_id
    features = NULL
)
```

2024-06-04 05:23 UTC, merged

2024-06-04 05:23 UTC, stemangiola commented
Thanks @myushen !